language: python
python:
  - "3.6"
cache: pip
before_install:
  - openssl aes-256-cbc -K $encrypted_1c60200ecebb_key -iv $encrypted_1c60200ecebb_iv
    -in environment.yml.enc -out environment.yml -d
install:
  - pip install -r requirements.txt
script:
  - pylint --output-format=parseable team2_at08
  - behave --no-capture --tags @smoke,@acceptance,@positive,@negative --tags ~@wip --summary
notifications:
  email: True